/**
 *
 * Copyright 2011 (C) Rainer Schneider,Roggenburg <schnurlei@googlemail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Created on 19.06.2003
 *
 */
package de.jdynameta.base.metainfo;

import de.jdynameta.base.value.JdyPersistentException;


/**
 * @author Rainer Schneider
 */
public interface AttributeInfo 
{
	public String getInternalName();
	public String getExternalName();

	public String getAttrGroup();
	
	/**
	 * 
	 * @return Returns true - the attribute is generated by the Persistence layer  
	 */
	public boolean isGenerated();

	/**
	 * Returns the isKey.
	 * @return boolean
	 */
	public boolean isKey();

	/**
	 * Returns the isNotNull.
	 * @return boolean
	 */
	public boolean isNotNull();

	public void handleAttribute(AttributeHandler aHandler, Object aValue)
		throws JdyPersistentException;
}